import type { State, Provider } from "./model";
const shared = {
  city: "Ames, IA",
  days: [0, 1, 2, 3, 4, 5, 6],
  startHour: 8,
  endHour: 18,
};
export const seedProviders: Provider[] = [
  {
    ...shared,
    id: "p1",
    accountId: "a1",
    name: "Maya Thompson",
    title: "A fresh start for your home",
    bio: "Thoughtful home cleaning with a focus on kitchens, bathrooms, and the little details. Bring your priorities and I’ll take care of the rest. Cleaning supplies included.",
    category: "Cleaning",
    priceCents: 3500,
    pricing: "hourly",
    rating: 4.9,
    reviewCount: 48,
    color: "blue",
    experience: "5 years of experience",
  },
  {
    ...shared,
    id: "p2",
    accountId: "a2",
    name: "Arjun Patel",
    title: "Good food, made in your kitchen",
    bio: "Fresh home cooking and weekly meal prep. Vegetarian favorites, comforting dinners, and menus tailored to your preferences. Ingredients are purchased separately by the customer.",
    category: "Cooking",
    priceCents: 4500,
    pricing: "hourly",
    rating: 4.9,
    reviewCount: 32,
    color: "orange",
    experience: "8 years of experience",
  },
  {
    ...shared,
    id: "p3",
    accountId: "a3",
    name: "Jordan Brooks",
    title: "Car care that comes to you",
    bio: "Mobile vehicle diagnostics and basic maintenance. The fixed price covers a diagnostic visit; parts and additional repairs require a separate quote.",
    category: "Auto repair",
    priceCents: 8500,
    pricing: "fixed",
    rating: 4.8,
    reviewCount: 61,
    color: "purple",
    experience: "10 years of experience",
  },
  {
    ...shared,
    id: "p4",
    accountId: "a4",
    name: "Elena Rodriguez",
    title: "A spotless space, less effort",
    bio: "Reliable routine cleaning for busy households. Book a one-time refresh or come back for regular care. Supplies included; deep-clean tasks discussed in advance.",
    category: "Cleaning",
    priceCents: 3000,
    pricing: "hourly",
    rating: 4.8,
    reviewCount: 26,
    color: "green",
    experience: "4 years of experience",
  },
  {
    ...shared,
    id: "p5",
    accountId: "a5",
    name: "Sam Wilson",
    title: "Dinner plans, sorted",
    bio: "Weeknight meals and small dinner gatherings cooked at home. We’ll agree on a menu before your appointment. Ingredients are not included in the hourly rate.",
    category: "Cooking",
    priceCents: 4000,
    pricing: "hourly",
    rating: 4.7,
    reviewCount: 19,
    color: "pink",
    experience: "6 years of experience",
  },
  {
    ...shared,
    id: "p6",
    accountId: "a6",
    name: "Chris Anderson",
    title: "Keep your everyday drive moving",
    bio: "On-site basic car maintenance and inspections. This package includes a vehicle health check. Any parts, fluids, or additional work are quoted separately.",
    category: "Auto repair",
    priceCents: 6500,
    pricing: "fixed",
    rating: 4.9,
    reviewCount: 22,
    color: "gold",
    experience: "7 years of experience",
  },
];
export const seed: State = {
  accounts: seedProviders.map((p) => ({
    id: p.accountId,
    name: p.name,
    email: `${p.id}@example.test`,
    role: "provider" as const,
  })),
  providers: seedProviders,
  bookings: [],
  reviews: [],
  currentAccountId: null,
};
